baseurl: /lakshmikanthan.github.io
permalink : :title
heroimage: "images/heroimage.jpeg"
title: Lakshmikanthan Paramanthan
author-image: "images/heroimage2.jpeg"
author-name: Laksh
author-about: Aspiring Full Stack Dev
email: paramanathan.lakshmikanthan@gmail.com
twitter_username: kantpillai
linkedin_username: lakshmikanthan-paramanathan-4a57b840
github_username: LakshmikanthanP